washingtonstateuniversity/WSUWP-Content-Syndicate

- wsuwp-content-syndicate.php
This is a horrible work around, but it appears that we can not
yet rely on the post date being passed with the JSON response.
> [PR] If a post date is not passed, use the current time.

- wsuwp-content-syndicate.php
I'm not sure if this will break something, but it's super confusing that I had it there in the first place and is causing events to show up in a strange order when embedded on other sites.
> [PR] Don't reverse sort by date when pulling events.

- wsuwp-content-syndicate.php
A comma separated list of event categories is now supported in
the shortcode
> [PR] Provide support for multiple category slugs in events feed

- wsuwp-content-syndicate.php
Adds a `site` attribute to be used for specifying a full URL when a hostname does not suffice.
Fixes #22
> [PR] Support a full site URL with path rather than only bare hosts

- wsuwp-content-syndicate.php
Previously, if a count was not specified, the default of false
would create a situation where no items would be shown. We should
instead fall back to the number of items offered by the requested
site.
> [PR] If a count is not specified, don't limit the count

- includes/syndicate-shortcode-events.php
When we moved to WP-API v2, the old endpoint for retrieving events
was made invalid and changed to `/events/`. This adjusts the logic
building the query accordingly.
> [PR] Provide support for new `/events/` endpoint with event categories

- includes/syndicate-shortcode-base.php
- includes/syndicate-shortcode-events.php
- includes/syndicate-shortcode-json.php
- includes/syndicate-shortcode-people.php
#41 from @philcable got lost a bit during the transition to the new WP-API. I'm going to cherry-pick some commits from that branch and apply them to master.
* Provide support for university location in all shortcodes with `university_location_slug` attribute.
* Pass `$atts` as additional context to `wsuwp_people_sort_items` filter.
* Include the shorcode name as a third parameter of `shortcode_atts()` to allow for use of the `shortcode_atts_{$shortcode}` filter.
There are two other commits I'm going to open in another PR for some continued discussion.
> [PR] Implement previously suggested changes from CAHNRS

- includes/syndicate-shortcode-json.php
Primarily for styling purposes on the IP site news feed, but also for consistency. @jeremyfelt #reviewmerge?
> [PR] Remove line break inside `content-item-thumbnail`

- includes/syndicate-shortcode-base.php
- includes/syndicate-shortcode-json.php
When this plugin is used in multisite to share content between
sites, the large majority of requests will be made to sites that
do not require an HTTP connection. Instead, we can take advantage
of the direct REST API methods available to us.
Introduces the `scheme` attribute, which lets a user choose local
or http. We may build this out to help determine HTTP or HTTPS in
the future.
> [PR] Use direct REST API methods when available vs HTTP requests

- includes/syndicate-shortcode-base.php
- includes/syndicate-shortcode-json.php
This clarifies the code we were using for the wsuwp_json shortcode to determine whether or not a local or remote request should be made. I've moved it to the base class so that it can become available for other shortcodes as well.
By default, "local" is used for the scheme attribute. If used in a multisite configuration, we'll always look to see if a local request can be made. "http" or "https" can be passed to override this behavior and make an external request at all times. This can be useful in multisite if a plugin or theme is enabled on that other site that adds specific functionality to a post that would not be available with `switch_to_blog()`.
In the process of clarifying this, support for single site is now provided. We had previously used `get_blog_details()`, which is a …
> [PR] Support explicit "remote" requests

- includes/syndicate-shortcode-events.php
I'm not sure what the upstream change is yet, but the old posts
per page filter is no longer limiting the number of events that
are pulled from the REST API.
We'll need to dig in closer to determine the root cause.
> [PR] Use per_page for events vs filter[posts_per_page]

- includes/syndicate-shortcode-people.php
I think the same upstream change that impacted the events post
type is effecting the people post type.
@jeremyfelt #reviewmerge?
> [PR] Use per_page for people vs filter[posts_per_page]

- includes/syndicate-shortcode-people.php
The WP REST API expects this value to be between 0 and 100, so we'll provide
100 if the shortcode's `count` attribute happens to be greater than that :)
> [PR] Provide a maximum value for the `per_page` query argument

- includes/syndicate-shortcode-base.php
- includes/syndicate-shortcode-json.php
Previously, we treated all requests to sites in the multisite install as "local" rather than making HTTP requests to retrieve content. Because of how filters are applied, any content filtering would happen in the context of the current site rather than the requested site. For the most part this does not cause an issue, but can create confusing situations when the configurations of sites start to become less alike.
Moving back to remote requests keeps things simple. :)
> [PR] Treat only requests to current site as local

- includes/syndicate-shortcode-json.php
`esc_attr()` was doing some things that broke the JSON object output
mid page.
> [PR] Sanitize with `wp_json_encode()` and not `esc_attr()`

- includes/class-wsu-syndicate-shortcode-json.php
The existing filter for this allows custom code to override the output HTML after it has been generated by the plugin.
This new filter provides the ability to override the output completely and have that cached in the main plugin rather than having to duplicate work.
> [PR] Allow the complete override of syndicate output

- includes/class-wsu-syndicate-shortcode-json.php
This provides more data about a post's feature media to the content syndicate plugin and any custom code extending it through filters.
In making this change, we're also adjusting the format of local results. When a local REST request is made, the data is returned as an array as opposed to an object like a remote request. This causes
confusion because each use the same filter to allow the modification of response data.
This converts local results to use an object instead. It will have an impact on the [research.wsu.edu theme](https://github.com/washingtonstateuniversity/research.wsu.edu/blob/4dc7d1c724b8f9dcdaccdf99f00b84a0e2e6957b/functions.php#L78), which appears to be the only one that actually uses the array data at this point.
That theme will need to be updated at the same time as …
> [PR] Update feature media support

- includes/class-wsu-syndicate-shortcode-base.php
- includes/class-wsu-syndicate-shortcode-json.php
This extends any extended attributes so that they can be applied to results requested from the local site via `local_count`. As an example, `[wsuwp_json count=10 local_count=2 local_tag=blue]` will
pull in 2 local posts tagged as "blue" and merge them with the 10 remote results that don't have any tag restrictions. `[wsuwp_json count=10 local_count=3 tag="taco" local_tag="burrito"]` will merge local burrito posts with remote taco posts.
In refactoring for this, local results are now retrieved with a local REST request as opposed to a WP Query. This makes it easier for the data format to match as expected.
> [PR] Handle `local_` prefixed shortcode attributes

- includes/class-wsu-syndicate-shortcode-json.php
- includes/content-syndicate.php
- wsuwp-content-syndicate.php
This separates how local results and remote results are cached. Rather than caching the entire shortcode display, we get a bit more granular. The processed data from each REST request (internal or external) is cached rather than the entire set of shortcode data. This allows us to clear the cache for local results whenever a post is published, updated, or trashed.
> [PR] Improve caching and cache busting of local results

- includes/class-wsu-syndicate-shortcode-json.php
These are now part of the WSU taxonomy extension to content syndicate.
> [PR] Remove old taxonomy docs

- includes/class-wsu-syndicate-shortcode-json.php
In 211a4bcf5f6832e717836d4e476417ed0d7c70cf, the cache key used to store results from remote requests was changed to be different from the cache key used to retrieve them. Since this change, no remote request has been effectively cached. 🎉 
This corrects the key to match how cache is stored.
> [PR] Correct the cache key used for looking up cached results

- includes/class-wsu-syndicate-shortcode-json.php
This helps in at least two ways:
* Reduce the size of the REST API responses by not including large blocks of content when they are not used.
* Avoid processing shortcodes unnecessarily in content that is being requested in Content Syndicate. This specifically avoids an infinite loop when the page requesting the headlines is also one of the headlines being returned.
Some weird white space changes in this, so adding w=1 to the URL may help - https://github.com/washingtonstateuniversity/WSUWP-Content-Syndicate/compare/headline-titles-only?expand=1&w=1
> [PR] Only request title and link when outputting headlines

- includes/class-wsu-syndicate-shortcode-json.php
The `thumbnail` size is returning the correct image, so i've gone ahead and just prioritized it over the `post-thumbnail` field.
> Prioritize thumbnails for displaying cropped images properly

- includes/class-wsu-syndicate-shortcode-json.php
These changes will address thumbnails on local feeds, where as #111 addressed remote feeds.
Should close out #110.
> Force thumbnails to override featured images on local feeds
